<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ee.cyber.cdoc2</groupId>
        <artifactId>cdoc2-rp-server</artifactId>
        <version>0.5.0-SNAPSHOT</version>
    </parent>

    <artifactId>cdoc2-rp-server-openapi</artifactId>

    <properties>
        <cdoc2-rp-server-openapi.version>0.9.0-draft-snapshot</cdoc2-rp-server-openapi.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <swagger-annotations.version>2.2.22</swagger-annotations.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ee.cyber.cdoc2.openapi</groupId>
            <artifactId>cdoc2-rp-server-openapi</artifactId>
            <version>${cdoc2-rp-server-openapi.version}</version>
            <type>yaml</type>
        </dependency>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-annotations.version}</version>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.1.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.1.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.10.0</version>
                <executions>

                    <execution>
                        <id>copy-cdoc2-rp-server-openapi-yaml</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>ee.cyber.cdoc2.openapi</groupId>
                                    <artifactId>cdoc2-rp-server-openapi</artifactId>
                                    <version>${cdoc2-rp-server-openapi.version}</version>
                                    <type>yaml</type>
                                    <outputDirectory>${project.build.directory}/openapi</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                            <useBaseVersion>true</useBaseVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.20.0</version>
                <executions>
                    <execution>
                        <id>generate-rp-server</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.build.directory}/openapi/cdoc2-rp-server-openapi-${cdoc2-rp-server-openapi.version}.yaml
                            </inputSpec>
                            <apiPackage>ee.cyber.cdoc2.server.adapter.generated.api</apiPackage>
                            <modelPackage>ee.cyber.cdoc2.server.adapter.generated.model</modelPackage>
                        </configuration>
                    </execution>

                </executions>
                <configuration>
                    <generatorName>spring</generatorName>
                    <!-- Without this some broken openapi classes are generated that use old 2.x springfox API -->
                    <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                    <generateAliasAsModel>false</generateAliasAsModel>
                    <configOptions>
                        <useSpringBoot4>true</useSpringBoot4>
                        <useTags>true</useTags>
                        <useJackson3>true</useJackson3>
                        <openApiNullable>false</openApiNullable>
                        <delegatePattern>true</delegatePattern>
                        <dateLibrary>java8</dateLibrary>
                        <hateoas>false</hateoas>
                        <oas3>true</oas3>
                        <useOptional>false</useOptional>
                        <bigDecimalAsString>true</bigDecimalAsString>
                        <enumUnknownDefaultCase>true</enumUnknownDefaultCase>
                        <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                        <!-- requestMappingMode: https://github.com/OpenAPITools/openapi-generator/pull/13838 -->
                        <requestMappingMode>none</requestMappingMode>&gt;
                    </configOptions>
                    <typeMappings>
                        <typeMapping>duration=Duration</typeMapping>
                    </typeMappings>
                    <importMappings>Duration=java.time.Duration</importMappings>
                </configuration>
            </plugin>
        </plugins>

    </build>

</project>