spring.datasource.url=jdbc:postgresql://localhost:7433/cdoc2rp
spring.datasource.username=docker
spring.datasource.password=docker
spring.datasource.driver-class-name=org.postgresql.Driver

app.smartid.client.hostUrl=https://sid.demo.sk.ee/smart-id-rp/v3/

spring.ssl.bundle.jks.sid-server.truststore.location=classpath:demo_server_trusted_ssl_certs.jks
spring.ssl.bundle.jks.sid-server.truststore.password=changeit
spring.ssl.bundle.jks.sid-server.truststore.type=jks
