server.port=9080

spring.datasource.url=jdbc:postgresql://localhost:7433/cdoc2rp
spring.datasource.username=docker
spring.datasource.password=docker
spring.datasource.driver-class-name=org.postgresql.Driver

app.smartid.client.hostUrl=https://sid.demo.sk.ee/smart-id-rp/v3/

spring.ssl.bundle.jks.sid-server.truststore.location=classpath:demo_server_trusted_ssl_certs.jks
spring.ssl.bundle.jks.sid-server.truststore.password=changeit
spring.ssl.bundle.jks.sid-server.truststore.type=jks

spring.ssl.bundle.jks.sid-trusted-issuers.truststore.location=file:test_sid_trusted_issuers.jks
spring.ssl.bundle.jks.sid-trusted-issuers.truststore.password=changeit
spring.ssl.bundle.jks.sid-trusted-issuers.truststore.type=jks

app.rp.name=DEMO
app.rp.uuid=00000000-0000-4000-8000-000000000000
app.rp.certificate-level=QUALIFIED
app.rp.scheme-name=smart-id-demo

app.restclient.auth-server.hostUrl=http://localhost:7500
